"""init_products_table

Revision ID: 215c878147c8
Revises: 
Create Date: 2025-11-28 18:42:29.574704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215c878147c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False, comment='本地唯一的SKU'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='商品标题'),
    sa.Column('price', sa.Float(), nullable=False, comment='建议售价'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='货币单位'),
    sa.Column('stock_qty', sa.Integer(), nullable=False, comment='本地库存数量'),
    sa.Column('description_original', sa.Text(), nullable=True, comment='原始采集的描述'),
    sa.Column('description_ai', sa.Text(), nullable=True, comment='AI 重写后的营销描述'),
    sa.Column('seo_keywords', sa.String(length=500), nullable=True, comment='AI 生成的SEO关键词,逗号分隔'),
    sa.Column('is_ai_optimized', sa.Boolean(), nullable=False, comment='是否已完成AI优化'),
    sa.Column('images', sa.JSON(), nullable=True, comment="图片URL列表 ['http://...', 'http://...']"),
    sa.Column('video_url', sa.String(length=500), nullable=True, comment='AI 生成的短视频地址'),
    sa.Column('source_url', sa.String(length=500), nullable=True, comment='采购来源URL (如 AliExpress/1688)'),
    sa.Column('supplier_cost', sa.Float(), nullable=False, comment='采购成本价'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: draft, published, archived'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_title'), 'products', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_title'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
