"""add owner_id to products

Revision ID: aaecaf925e9d
Revises: eb7f56682349
Create Date: 2025-11-28 21:34:59.089237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaecaf925e9d'
down_revision: Union[str, Sequence[str], None] = 'eb7f56682349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('owner_id', sa.Integer(), nullable=False, comment='所属用户ID'))
    op.create_foreign_key(None, 'products', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'owner_id')
    # ### end Alembic commands ###
